Feature/article
ESIR-SI-2020/Queries pull request #4
Opened 2019-10-15 12:07 UTC by nrc97

feature article: updated User model, services and controller, and added Article model and ArticleConsultationDTO model

2019-10-15 12:41 UTC, Kevin-Philip requested changes

2019-10-15 12:41 UTC, Kevin-Philip commented on app/pom.xml
> +        </dependency>
Tu l'utilises où ?

2019-10-15 12:41 UTC, Kevin-Philip commented on app/src/main/java/com/jxc/app/controllers/UserController.java
> +    }
On va plutôt mettre les APIs d'articles dans une classe ArticleController

2019-10-15 12:41 UTC, Kevin-Philip commented on app/src/main/java/com/jxc/app/models/Article.java
> +}
```suggestion
@Data
@NoArgsConstructor
@AllArgsConstructor
@RequiredArgsConstructor
public class Article {

    @NonNull
    private String id;
    @NonNull
    private String url;

    private List<String> tags;
    private List<String> suggestedTags;

}
```

2019-10-15 12:41 UTC, Kevin-Philip commented on app/src/main/java/com/jxc/app/models/ArticleConsultationDTO.java
> +    @Id
pk @Id ?

2019-10-15 12:41 UTC, Kevin-Philip commented on app/src/main/java/com/jxc/app/models/User.java
> +import lombok.*;
On va essayer d'éviter les import * . Automatiquement, IntelliJ te converti 5 imports ou plus d'une même librairie en import * , à changer dans les options d'IntelliJ :
Settings > Editor > Code Style > Java > Imports > Class count to use import with ''*".

2019-10-15 12:41 UTC, Kevin-Philip commented on app/src/main/java/com/jxc/app/services/UserService.java
> +
On va préférer faire un ArticleService et un ArticleServiceImp pour les méthodes qui traitent des Articles

2019-10-15 12:41 UTC, Kevin-Philip commented on app/src/main/java/com/jxc/app/services/UserServiceImp.java
> +
On va plutôt utiliser un mapper, même si c'est overkill ça permettra de découvrir comment ça fonctionne et d'avoir un truc propre

2019-10-15 12:41 UTC, Kevin-Philip commented on app/src/main/java/com/jxc/app/controllers/UserController.java
> +                });
C'est correct, ça fonctionne, mais vu qu'ici on a un service, on va plutôt mettre la logique dedans.

2019-10-15 12:41 UTC, Kevin-Philip commented on app/src/main/java/com/jxc/app/controllers/UserController.java
> +                .collect(Collectors.toList());
pareil

2019-10-15 12:41 UTC, Kevin-Philip commented on app/src/main/java/com/jxc/app/controllers/UserController.java
> +                });
pareil

2019-10-15 12:54 UTC, nrc97 commented on app/pom.xml
> +        </dependency>
J'ai oublié de retirer cette dépendance
Je voulais l'utiliser dans la fonction articleToArticleConsultationDTO de UserService pour la conversion de Article vers ArticleConsultation mais bon finalement j'ai décidé de le faire sans elle

2019-10-15 12:55 UTC, nrc97 commented on app/src/main/java/com/jxc/app/controllers/UserController.java
> +    }
ok

2019-10-15 13:23 UTC, nrc97 commented on app/src/main/java/com/jxc/app/models/ArticleConsultationDTO.java
> +    @Id
Je sais pas si c'est correct mais j'ai voulu faire exactement  comme pour la classe Article...

2019-10-15 13:26 UTC, Kevin-Philip commented on app/src/main/java/com/jxc/app/models/ArticleConsultationDTO.java
> +    @Id
Pour les models qui sont pas stockés en base je vois pas trop d'intérêt de définir une primary key

2019-10-16 11:46 UTC, AntoineCheron requested changes

2019-10-16 11:46 UTC, AntoineCheron commented on app/src/main/java/com/jxc/app/controllers/ArticleController.java
> +
Un saut de ligne en trop

2019-10-16 11:46 UTC, AntoineCheron commented on app/src/main/java/com/jxc/app/controllers/ArticleController.java
> +import org.springframework.beans.factory.annotation.Autowired;
Ajoute un saut de ligne pour séparer les imports de ton projet de ceux des libs

2019-10-16 11:46 UTC, AntoineCheron commented on app/src/main/java/com/jxc/app/controllers/ArticleController.java
> +     */
Inutile ce commentaire, il dit la même chose que la signature

2019-10-16 11:46 UTC, AntoineCheron commented on app/src/main/java/com/jxc/app/controllers/ArticleController.java
> +    @GetMapping("/{email}/articles")
Mauvaise modélisation d'API, l'URL pour obtenir cette requete devrait être : 
`/api/v1/articles?owner={user.email}` ➜ la ressource manipulée est l'article, pas l'utilisateur.

Une exception `ResourceNotFoundException` suffirait, ici tu vas te retrouver à créer des exception spécifique pour chaque type de resource que tu ne trouves pas, ça fait beaucoup de nouvelles classes alors que je doute que tu utilises différemment `UserNotFoundException` de `ArticleNotFoundException`. Et à la limite si t'as besoin de savoir quelle ressource est manquante tu peux placer l'info dans l'exception.

2019-10-16 11:46 UTC, AntoineCheron commented on app/src/main/java/com/jxc/app/controllers/ArticleController.java
> +    @GetMapping("/{email}/articles/{articleId}")
Dès que nous aurons l'authentification en place, email ne servira plus à rien, on pourra récupérer l'id de l'utilisateur depuis son context et ainsi vérifier s'il est bien le pocesseur de la ressource demandée.

Ma remarque sur la modélisation de l'API tient aussi ici :). `/api/v1/articles/{articleId}` est plus adapté.

2019-10-16 11:46 UTC, AntoineCheron commented on app/src/main/java/com/jxc/app/controllers/ArticleController.java
> +    public ResponseEntity<List<ArticleConsultationDTO>> getUserSharedArticles(@PathVariable String email) throws UserNotFoundException, IOException {
Je vous recommande de gérer le côté shared via des query parameters dans la fonction `getUserArticles`. Il suffit de considérer que, si non fourni, `shared = false`. 
Vous pouvez aussi le gérer avec deux paramètres : `includeShared` `includePersonal`

2019-10-16 11:46 UTC, AntoineCheron commented on app/src/main/java/com/jxc/app/controllers/ArticleController.java
> +    @GetMapping("/{email}/articles/shared/{articleId}")
Useless, `/articles/{articleId}` suffit amplement. Ca réduit la complexité d'avoir moins d'API. Dans le cas présent la complexité commence déjà à grimper alors qu'on expose peu de choses ;).

2019-10-16 11:46 UTC, AntoineCheron commented on app/src/main/java/com/jxc/app/controllers/UserController.java
> +
Oulalalalalala je veux que ça disparaisse ça :)

2019-10-16 11:46 UTC, AntoineCheron commented on app/src/main/java/com/jxc/app/exceptions/ArticleNotFoundException.java
> +public class ArticleNotFoundException extends RuntimeException {
Ca confirme donc ce que je disais plus haut aha, vous pouvez remplacer par `ResourceNotFoundException`, ce sera suffisant ;)

2019-10-16 11:46 UTC, AntoineCheron commented on app/src/main/java/com/jxc/app/mappers/ArticleMapper.java
> +import com.jxc.app.models.dto.ArticleConsultationDTO;
Ajouter un saut de ligne en dessous (Intellij peut se configurer pour faire ça à votre place lorsque vous importez automatiquement)

2019-10-16 11:46 UTC, AntoineCheron commented on app/src/main/java/com/jxc/app/mappers/ArticleMapper.java
> +public class ArticleMapper {
Bonne initiative le mapper 👍

2019-10-16 11:46 UTC, AntoineCheron commented on app/src/main/java/com/jxc/app/mappers/ArticleMapper.java
> +        Document document = null;
Comme il n'est utilisé que dans le `try` il peut y être instancié

2019-10-16 11:46 UTC, AntoineCheron commented on app/src/main/java/com/jxc/app/mappers/ArticleMapper.java
> +            e.printStackTrace();
Utilisez un `Logger` svp, ça se fait bien avec Lombok et l'annotation `@Log4j2` (il faudra juste ajouter un fichier de conf Log4j dans `resources`

2019-10-16 11:46 UTC, AntoineCheron commented on app/src/main/java/com/jxc/app/mappers/ArticleMapper.java
> +        return document;
Vraiment inutile d'écrire tant de lignes. Pourquoi instancier document à null ? Ca crée des pointeurs pour rien, la fonction peut être : `return Jsoup.connect(url).get();`

2019-10-16 11:46 UTC, AntoineCheron commented on app/src/main/java/com/jxc/app/services/ArticleService.java
> +
Un saut de ligne en trop

2019-10-16 11:46 UTC, AntoineCheron commented on app/src/main/java/com/jxc/app/services/ArticleService.java
> +import org.springframework.http.ResponseEntity;
Manque un saut de ligne ici

2019-10-16 11:46 UTC, AntoineCheron commented on app/src/main/java/com/jxc/app/services/ArticleService.java
> +     */
Toujours inutile comme commentaire

2019-10-16 11:46 UTC, AntoineCheron commented on app/src/main/java/com/jxc/app/services/ArticleServiceImp.java
> +import com.jxc.app.models.dto.ArticleConsultationDTO;
Manque saut de ligne en dessous

2019-10-16 11:46 UTC, AntoineCheron commented on app/src/main/java/com/jxc/app/services/ArticleServiceImp.java
> +public class ArticleServiceImp implements ArticleService {
Généralement les gens l'appellent plutôt ArticleServiceImpl (avec un l à la fin)

2019-10-16 11:46 UTC, AntoineCheron commented on app/src/main/java/com/jxc/app/mappers/ArticleMapper.java
> +public class ArticleMapper {
Cette classe n'a pas d'état, toutes ses méthodes peuvent être rendues statiques

2019-10-16 11:46 UTC, AntoineCheron commented on app/src/main/java/com/jxc/app/services/ArticleServiceImp.java
> +    ArticleMapper articleMapper;
Je pense que ça ne va pas marcher, tu n'as pas annoté `ArticleMapper` comme étant un `@Service`. 

Si tu prends en compte mon commentaire, tu n'en n'auras plus besoin de toute manière :). Tu pourras direct appeler ses méthodes.

2019-10-16 11:46 UTC, AntoineCheron commented on app/src/main/java/com/jxc/app/services/UserServiceImp.java
> +
A supprimer

2019-10-16 11:46 UTC, AntoineCheron commented on app/src/main/java/com/jxc/app/services/UserService.java
> +
A supprimer

2019-10-16 11:46 UTC, AntoineCheron commented on app/src/main/java/com/jxc/app/services/ArticleServiceImp.java
> +        ArticleConsultationDTO article = this.userService.findUserById(email).getArticles().stream()
Les articles ne devraient pas être "dans" l'utilisateur mais à part. Ce sont des ressources à part entière. Procéder ainsi réduit le couplage entre vos données et permet de faire évoluer le code plus facilement ;). Essayez un minimum de mettre des ressources à l'intérieur d'autres, utilisez plutôt des références entre elles (à la manière des clés secondaires en SQL)

2019-10-16 11:46 UTC, AntoineCheron commented on app/src/main/java/com/jxc/app/services/ArticleServiceImp.java
> +                .filter(articleElement -> articleId.equals(articleElement.getId())).findFirst()
Devrait être fait directement en base, pas en mémoire

2019-10-21 11:13 UTC, AntoineCheron requested changes
Vous n'avez pas encore pris en compte mes commentaires, dont certains sont structurants, j'attends que ce soit fait pour valider ;)

2019-10-21 12:54 UTC, closed without merging